import type { Language } from './translations';
import { translations } from './translations';

// UI-owned copy only. Never translate customer names, addresses, or reviews.
export const uiCopy: Record<string, string> = {
  "అధీకృత యజమాని యాక్సెస్ మాత్రమే": "Authorized owner access only",
  "మూసివేయండి": "Close",
  "• కొల్లూరు": "• Kollur",
  "లేదా": "or",
  "ఎంచుకోండి.": "Select an option.",
  "మన ఇంటి వంట (Mana Enti Vanta) Rotis": "Mana Enti Vanta Rotis",
  "మన ఇంటి వంట - అచ్చమైన పల్లెటూరి రుచులు": "Mana Enti Vanta - Authentic village flavours",
  "మన ఇంటి వంట": "Mana Enti Vanta",
  "అచ్చమైన పల్లెటూరి రుచులు": "Authentic village flavours",
  "భాష మార్చండి / Change Language": "Change language",
  "Android యాప్ డౌన్‌లోడ్ / Install App": "Install Android app",
  "నా ఆర్డర్లు — ఆర్డర్ స్థితి చూడండి / My Orders — Track your order": "My Orders — Track your order",
  "యజమాని సంప్రదించండి": "Call the owner",
  "లైట్ మోడ్": "Light mode",
  "డార్క్ మోడ్": "Dark mode",
  "కొల్లూరు • Kolluru": "Kollur",
  "భాషను ఎంచుకోండి / Choose Language:": "Choose language:",
  "ఆఫ్‌లైన్ మోడ్ — కాషింగ్ డేటా అందుబాటులో ఉంది": "You are offline. Saved pages are available; reconnect to order or track deliveries.",
  "కాపీ అయింది": "Copied",
  "కీ కాపీ చేయి": "Copy key",
  "రసీదు కాపీ చేయి": "Copy receipt",
  "ఆర్డర్ నంబర్ బదులు కన్ఫర్మేషన్‌లో ఇచ్చిన ట్రాకింగ్ కీ నమోదు చేయండి (Enter your tracking key).": "Enter the private tracking key from your confirmation, not the order number.",
  "ఆర్డర్ కనుగొనబడలేదు.": "Order not found.",
  "ఈ కీతో ఆర్డర్ వివరాలు లభించలేదు.": "No order was found for this tracking key.",
  "సర్వర్ కనెక్షన్ లోపం ఏర్పడింది. దయచేసి మళ్లీ ప్రయత్నించండి.": "Unable to connect. Please try again.",
  "ట్రాకింగ్ కీ ద్వారా వెతకండి (Enter tracking key):": "Search with your private tracking key:",
  "ఆర్డర్ కన్ఫర్మేషన్‌లో ఇచ్చిన కీ / Tracking key": "Tracking key from your order confirmation",
  "వెతుకుతోంది...": "Searching...",
  "వెతకండి": "Search",
  "రొట్టెలు)": "items)",
  "కస్టమర్ పేరు:": "Customer name:",
  "కస్టమర్": "Customer",
  "రొట్టెల పరిమాణం:": "Order quantity:",
  "వస్తువులు (₹": "items (₹",
  "డెలివరీ తేదీ:": "Delivery date:",
  "విశ్లేషణ డేటాను లోడ్ చేస్తోంది...": "Loading analytics...",
  "మొత్తం ఆదాయం": "Total revenue",
  "నేటి రాబడి: ₹": "Today's revenue: ₹",
  "ఆర్డర్లు)": "orders)",
  "విక్రయాలు (పదార్థాలు)": "Items sold",
  "జొన్న +": "jowar rotis +",
  "చపాతీ": "chapathis",
  "సగటు రేటింగ్": "Average rating",
  "కస్టమర్ సమీక్షలు": "customer reviews",
  "కరివేపాకు కారం": "Curry leaf karam",
  "గ్రా.": "g",
  "ఉచితంగా అందించినది": "Provided free",
  "అవిసె గింజల కారం": "Flax seed karam",
  "గంటల వారీ ఆర్డర్ల రద్దీ (Hourly Peak Ordering Volume)": "Orders by hour",
  "ఆర్డరింగ్ వేళలు: 11:00 AM – 4:00 PM IST": "Ordering hours: 11:00 AM – 4:00 PM IST",
  "ఆర్డర్లు": "orders",
  "ఆర్డర్ల నిర్వహణ స్థితి (Status)": "Order status",
  "డెలివరీ పురోగతి వర్గీకరణ": "Delivery progress overview",
  "ఆర్డర్ అందింది (Received)": "Received",
  "తయారవుతోంది (Preparing)": "Preparing",
  "డెలివరీలో ఉంది (Out for delivery)": "Out for delivery",
  "డెలివరీ పూర్తయింది (Delivered)": "Delivered",
  "డెలివరీ సమయ కిటికీ:": "Delivery window:",
  "సాయంత్రం 6:00 – 8:00 గంటలు": "6:00 – 8:00 PM",
  "లావాదేవీల ఆడిట్ రికార్డులు (Transaction & Security Audit Logs)": "Transaction & security audit logs",
  "సర్వర్ ద్వారా నమోదైన అన్ని చెల్లింపులు మరియు ఆర్డర్ స్థితి మార్పుల వివరాలు": "Server records of payments and order status changes",
  "మొత్తం రికార్డులు:": "Total records:",
  "సమయం (IST / UTC)": "Time (IST / UTC)",
  "రకం / చర్య": "Type / action",
  "లక్ష్యం / ఆర్డర్": "Target / order",
  "వివరాలు": "Details",
  "కర్త (Actor)": "Actor",
  "ఇంకా ఎలాంటి ఆడిట్ రికార్డులు నమోదు కాలేదు.": "No audit records yet.",
  "🫓 రొట్టెల మెత్తదనం & రుచి": "🫓 Soft and tasty rotis",
  "🔥 వేడివేడిగా అందింది": "🔥 Hot and fresh",
  "🌿 కరివేపాకు కారం అదిరింది": "🌿 Delicious curry leaf karam",
  "🌰 అవిసె గింజల కారం బాగుంది": "🌰 Delicious flax seed karam",
  "⏱️ సమయానికి డెలివరీ": "⏱️ On-time delivery",
  "📦 పరిశుభ్రమైన ప్యాకింగ్": "📦 Clean packaging",
  "సగటు కస్టమర్ రేటింగ్ (Average Rating)": "Average customer rating",
  "సమీక్షలు)": "reviews)",
  "రేటింగ్ల విభజన (Rating Breakdown)": "Rating breakdown",
  "ఫిల్టర్:": "Filter:",
  "అన్నీ (": "All (",
  "కస్టమర్ లేదా కామెంట్ శోధించండి...": "Search customers or comments...",
  "రీఫ్రెష్ చేయండి": "Refresh",
  "ఈ కేటగిరీలో ఎలాంటి సమీక్షలు లేవు.": "No reviews in this category.",
  "గౌరవనీయ కస్టమర్": "Customer",
  "ఆర్డర్:": "Order:",
  "వ్యాఖ్యలు లేవు (నక్షత్రాల రేటింగ్ మాత్రమే ఇవ్వబడింది).": "No comment (star rating only).",
  "CSV ఫైల్ విజయవంతంగా డౌన్‌లోడ్ అయింది!": "CSV downloaded successfully!",
  "PDF రిపోర్ట్ విజయవంతంగా డౌన్‌లోడ్ అయింది!": "PDF downloaded successfully!",
  "రిపోర్ట్స్ ఎక్స్‌పోర్ట్ (Export Reports)": "Export reports",
  "CSV లేదా PDF ఫార్మాట్‌లలో ఆర్డర్లు మరియు ఆదాయ సమాచారాన్ని డౌన్‌లోడ్ చేయండి": "Download orders and revenue as CSV or PDF",
  "ఫార్మాట్ ఎంచుకోండి (Select Format):": "Choose a format:",
  "CSV స్ప్రెడ్‌షీట్ (.csv)": "CSV spreadsheet (.csv)",
  "PDF డాక్యుమెంట్ (.pdf)": "PDF document (.pdf)",
  "నిర్దిష్ట తేదీ ఫిల్టర్ (ఐచ్ఛికం):": "Filter by date (optional):",
  "తేదీ ఫిల్టర్ తొలగించు (అన్ని ఆర్డర్లు)": "Clear date filter (all orders)",
  "ఎక్స్‌పోర్ట్ కానున్న ఆర్డర్లు:": "Orders to export:",
  "మొత్తం ఆదాయం:": "Total revenue:",
  "డౌన్‌లోడ్ చేయండి": "Download",
  "మూసివేయి": "Close",
  "రద్దు చేయబడింది (Cancelled)": "Cancelled",
  "కొల్లూరు కిచెన్ & డెలివరీ నిర్వహణ | Asia/Kolkata Business Time": "Kollur kitchen & delivery management | India Standard Time",
  "సౌండ్ ఆన్": "Sound on",
  "సౌండ్ ఆఫ్": "Sound off",
  "రిఫ్రెష్": "Refresh",
  "CSV రిపోర్ట్": "CSV report",
  "లాగౌట్": "Log out",
  "స్టేటస్:": "Status:",
  "అన్నీ (All)": "All",
  "క్లియర్": "Clear",
  "ఫిల్టర్లు క్లియర్ చేసి మళ్ళీ ప్రయత్నించండి.": "Clear the filters and try again.",
  "రొట్టెలు: ₹": "Items: ₹",
  "+ డెలివరీ: ₹": "+ delivery: ₹",
  "ఆర్డర్ చేసిన పదార్థాలు:": "Ordered items:",
  "జొన్న రొట్టెలు:": "Jowar rotis:",
  "చపాతీలు:": "Chapathis:",
  "కారం (ఉచితం):": "Complimentary karam:",
  "దూరం:": "Distance:",
  "కి.మీ.": "km",
  "గుర్తు:": "Landmark:",
  "మ్యాప్స్ డైరెక్షన్స్": "Map directions",
  "స్టేటస్ మార్చు:": "Change status:",
  "తయారవుతోంది": "Preparing",
  "డెలివరీలో ఉంది": "Out for delivery",
  "డెలివరీ పూర్తయింది": "Delivered",
  "రద్దు": "Cancel",
  "🌾 రొట్టెల రుచి & మెత్తదనం (Soft & Tasty)": "🌾 Soft and tasty",
  "🔥 వేడివేడిగా అందింది (Hot & Fresh)": "🔥 Hot and fresh",
  "🌶️ కారాల రుచి అద్భుతం (Super Karam)": "🌶️ Delicious karam",
  "⏰ సమయానికి డెలివరీ (On-time Delivery)": "⏰ On-time delivery",
  "🏡 స్వచ్ఛమైన ఇంటి వంట (Hygienic Home Food)": "🏡 Hygienic home cooking",
  "🤝 చక్కని స్పందన (Polite Delivery)": "🤝 Polite delivery service",
  "ట్రాకింగ్ కీతో ఆర్డర్ తెరిచి మళ్లీ ప్రయత్నించండి (A tracking key is required).": "Open the order with your tracking key and try again.",
  "ఆర్డర్ అందినట్లుగా ధృవీకరించబడింది! దయచేసి క్రింద మీ రేటింగ్ మరియు అభిప్రాయాన్ని తెలపండి.": "Delivery confirmed! Please share your rating and feedback below.",
  "ఆర్డర్ స్థితి అప్‌డేట్ చేయడంలో లోపం ఏర్పడింది.": "Unable to update the order status.",
  "సర్వర్ కనెక్షన్ లోపం. దయచేసి మళ్లీ ప్రయత్నించండి.": "Connection error. Please try again.",
  "దయచేసి నక్షత్రాల రేటింగ్ ఎంచుకోండి.": "Please select a star rating.",
  "అభిప్రాయం మరియు హైలైట్లు కలిపి 500 అక్షరాలలోపు ఉండాలి (Maximum 500 characters including highlights).": "Keep your review and highlights within 500 characters.",
  "ఫీడ్‌బ్యాక్ సమర్పించడంలో లోపం ఏర్పడింది.": "Unable to submit feedback.",
  "డెలివరీ ధృవీకరణ & కస్టమర్ అభిప్రాయం (Delivery & Feedback)": "Delivery confirmation & feedback",
  "ఆర్డర్ నంబర్:": "Order number:",
  "చేరింది (Delivered)": "Delivered",
  "ప్రస్తుత డెలివరీ స్థితి:": "Current delivery status:",
  "డెలివరీ కోసం బయలుదేరింది (6-8 PM)": "Out for delivery (6–8 PM)",
  "నమోదైంది (కొత్తది)": "Order received",
  "మీ చేతికి వేడివేడి జొన్న రొట్టెల ఆర్డర్ అందిన తర్వాత క్రింది బటన్ నొక్కండి.": "Tap the button below only after you receive your food.",
  "నమోదవుతోంది...": "Saving...",
  "రొట్టెలు అందాయి (Confirm Received)": "Confirm delivery received",
  "అందుకున్నారు": "Received",
  "మీరు సమర్పించిన రేటింగ్:": "Your submitted rating:",
  "సవరించండి": "Edit",
  "సమర్పించినవారు:": "Submitted by:",
  "జొన్న రొట్టెల అనుభవం ఎలా ఉంది? (Rate your experience)": "Rate your experience",
  "అద్భుతం! (5/5)": "Excellent! (5/5)",
  "చాలా బాగుంది (4/5)": "Very good (4/5)",
  "బాగుంది (3/5)": "Good (3/5)",
  "మీకు బాగా నచ్చిన విషయాలు (Select Highlights):": "What did you like? Select highlights:",
  "మరిన్ని అభిప్రాయాలు లేదా సూచనలు (Comments / Suggestions):": "Comments or suggestions:",
  "ఉదా: రొట్టెలు చాలా మెత్తగా ఉన్నాయి, కరివేపాకు కారం అదిరిపోయింది...": "For example: The rotis were soft and the curry leaf karam was delicious...",
  "మీ పేరు (Name for review):": "Your name for the review:",
  "మీ పేరు": "Your name",
  "సమర్పిస్తోంది...": "Submitting...",
  "అభిప్రాయం సమర్పించండి (Submit Review)": "Submit review",
  "రద్దు చేయండి (Cancel)": "Cancel",
  "మీ విలువైన అభిప్రాయానికి చాలా ధన్యవాదాలు! ఇది ఇతర కస్టమర్లకు సహాయపడుతుంది.": "Thank you for your feedback! It helps other customers."
};

export function translateUi(text: string, language: Language): string {
  if (language === 'en') return uiCopy[text] ?? text;
  return Object.entries(uiCopy).find(([, english]) => english === text)?.[0] ?? text;
}

export function paymentStatusLabel(status: string, language: Language): string {
  const labels: Record<string, [string, string]> = {
    PAID: ['చెల్లింపు పూర్తయింది', 'Paid'],
    PENDING: ['చెల్లింపు పెండింగ్‌లో ఉంది', 'Payment pending'],
    FAILED: ['చెల్లింపు విఫలమైంది', 'Payment failed'],
    REFUNDED: ['డబ్బు తిరిగి చెల్లించబడింది', 'Refunded'],
  };
  return labels[status]?.[language === 'te' ? 0 : 1] ?? status;
}

const errorCopy: Record<string, string> = {
  'Invalid username or password credentials.': 'యూజర్‌నేమ్ లేదా పాస్‌వర్డ్ సరిగా లేదు.',
  'Please enter username and password.': 'దయచేసి యూజర్‌నేమ్ మరియు పాస్‌వర్డ్ నమోదు చేయండి.',
  'Login failed. Please check credentials.': 'లాగిన్ విఫలమైంది. వివరాలు తనిఖీ చేయండి.',
  'Failed to connect to authentication server.': 'సర్వర్‌తో కనెక్ట్ కావడం సాధ్యపడలేదు.',
  'Invalid or missing customer tracking access token.': 'ట్రాకింగ్ కీ సరిగా లేదు లేదా నమోదు చేయలేదు.',
  'No order matching this tracking access token was found.': 'ఈ ట్రాకింగ్ కీకి సంబంధించిన ఆర్డర్ కనబడలేదు.',
  'Invalid or missing customer access token.': 'ఆర్డర్ యాక్సెస్ కీ సరిగా లేదు లేదా నమోదు చేయలేదు.',
  'Unable to load orders. Please refresh.': 'ఆర్డర్లు లోడ్ కాలేదు. దయచేసి రిఫ్రెష్ చేయండి.',
  'Could not confirm order receipt.': 'ఆర్డర్ అందుకున్నట్లు నిర్ధారించలేకపోయాము. మళ్లీ ప్రయత్నించండి.',
  'Could not submit feedback.': 'అభిప్రాయం సమర్పించలేకపోయాము. మళ్లీ ప్రయత్నించండి.',
};

export function uiError(text: string, language: Language): string {
  const errorEnglish = errorCopy[text] ? text : Object.keys(errorCopy).find(key => errorCopy[key] === text);
  if (errorEnglish) return language === 'en' ? errorEnglish : errorCopy[errorEnglish]!;
  const translated = translateUi(text, language);
  if (translated !== text) return translated;
  const key = Object.keys(translations.en).find(key =>
    translations.en[key as keyof typeof translations.en] === text ||
    translations.te[key as keyof typeof translations.te] === text);
  if (key) return translations[language][key as keyof typeof translations.en];
  if (language === 'en' && /[\u0c00-\u0c7f]/.test(text)) return 'Unable to complete this request. Please check your details and try again.';
  if (language === 'te' && !/[\u0c00-\u0c7f]/.test(text)) return 'ఈ అభ్యర్థన పూర్తి కాలేదు. మీ వివరాలను సరిచూసి మళ్లీ ప్రయత్నించండి.';
  return text;
}
